import express from 'express'
import cors from 'cors'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Module host.
 *
 * Every Gospel module is a self-contained web app: its own UI, its own `/api`,
 * its own manifest, its own service worker scope and its own data directory. The
 * host can hand that app back in two shapes:
 *
 *   createModuleRouter()  mount inside the main Gospel app (e.g. /m/art-scan)
 *   createModuleApp()     run it alone on its own port, main app not required
 *
 * Both shapes serve identical code, so a module that works standalone works
 * mounted, and a broken main app cannot take Art Scan or Learning down with it.
 */

const sharedIconPath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'public',
  'gospel-kaiju.png',
)

/** Trailing-slash base path for the mount, e.g. "/" or "/m/art-scan/". */
function basePath(req) {
  const mount = req.baseUrl || ''
  return mount.endsWith('/') ? mount : `${mount}/`
}

function injectBase(html, base) {
  const tag = `<base href="${base}" />`
  // A single <base> lets one HTML file work at "/" and at "/m/<id>/" without
  // any path rewriting: relative URLs, fetch() and sw registration all follow.
  return html.includes('<base ')
    ? html
    : html.replace(/<head(\s[^>]*)?>/i, (match) => `${match}\n    ${tag}`)
}

function serviceWorkerSource({ base, cacheName, precache }) {
  return `// Generated by modules/host.js for base ${base}
const CACHE = ${JSON.stringify(cacheName)}
const BASE = ${JSON.stringify(base)}
const PRECACHE = ${JSON.stringify(precache)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).catch(() => {}),
  )
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return

  const url = new URL(req.url)
  if (url.origin !== location.origin || !url.pathname.startsWith(BASE)) return

  // API responses are live state. Caching them is what made the phone show a
  // stale module list long after the PC had moved on.
  if (url.pathname.startsWith(BASE + 'api/')) {
    event.respondWith(
      fetch(req).catch(
        () =>
          new Response(JSON.stringify({ ok: false, offline: true, message: 'Offline.' }), {
            status: 503,
            headers: { 'Content-Type': 'application/json' },
          }),
      ),
    )
    return
  }

  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone()
          caches.open(CACHE).then((cache) => cache.put(req, copy)).catch(() => {})
          return res
        })
        // Fall back to this module's own shell, never another app's page.
        .catch(() => caches.match(req).then((hit) => hit || caches.match(BASE))),
    )
    return
  }

  event.respondWith(
    caches.match(req).then((hit) => {
      const network = fetch(req)
        .then((res) => {
          if (res && res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((cache) => cache.put(req, copy)).catch(() => {})
          }
          return res
        })
        .catch(() => hit)
      return hit || network
    }),
  )
})
`
}

/**
 * Build the Express router for a module descriptor.
 * @param {object} descriptor
 */
export function createModuleRouter(descriptor) {
  const {
    id,
    name,
    publicDir,
    manifest = {},
    extraStatic = {},
    bodyLimit = '24mb',
    api,
  } = descriptor

  const router = express.Router()

  // Own body parser: modules accept whole PNG uploads, which are far larger
  // than the main app's 1mb JSON limit.
  router.use(express.json({ limit: bodyLimit }))

  const indexPath = path.join(publicDir, 'index.html')
  const serveIndex = (req, res) => {
    fs.readFile(indexPath, 'utf8', (err, html) => {
      if (err) {
        res.status(500).json({ ok: false, message: `Module “${id}” has no UI shell.` })
        return
      }
      res.type('html').send(injectBase(html, basePath(req)))
    })
  }

  router.get('/', serveIndex)
  router.get('/index.html', serveIndex)

  router.get('/manifest.webmanifest', (req, res) => {
    const base = basePath(req)
    res.type('application/manifest+json').json({
      id: base,
      name: manifest.name || name,
      short_name: manifest.short_name || name,
      description: manifest.description || descriptor.description || name,
      start_url: base,
      scope: base,
      display: 'standalone',
      background_color: manifest.background_color || '#0b0d0c',
      theme_color: manifest.theme_color || '#0b0d0c',
      icons: [
        { src: `${base}icon.png`, sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
      ],
    })
  })

  router.get('/sw.js', (req, res) => {
    const base = basePath(req)
    const precache = [base, `${base}app.js`, `${base}manifest.webmanifest`, `${base}icon.png`]
    for (const urlPath of Object.keys(extraStatic)) {
      precache.push(`${base}${urlPath.replace(/^\//, '')}`)
    }
    res
      .type('application/javascript')
      .set('Cache-Control', 'no-cache')
      .send(
        serviceWorkerSource({
          base,
          cacheName: `gospel-${id}-v1`,
          precache,
        }),
      )
  })

  router.get('/icon.png', (_req, res) => {
    res.sendFile(descriptor.iconPath || sharedIconPath)
  })

  const apiRouter = express.Router()
  apiRouter.get('/health', (req, res) => {
    // Inside the api sub-router baseUrl ends in /api; report the module root.
    const moduleBase = basePath({ baseUrl: req.baseUrl.replace(/\/api$/, '') })
    res.json({
      ok: true,
      module: id,
      name,
      version: descriptor.version || '1.0.0',
      kind: descriptor.kind || id,
      standalone: moduleBase === '/',
      mountedAt: moduleBase,
    })
  })
  if (typeof api === 'function') api(apiRouter, descriptor)
  router.use('/api', apiRouter)

  for (const [urlPath, filePath] of Object.entries(extraStatic)) {
    router.get(urlPath, (_req, res) => res.sendFile(filePath))
  }

  router.use(express.static(publicDir))

  return router
}

/** Wrap a module descriptor into a complete standalone Express app. */
export function createModuleApp(descriptor) {
  const app = express()
  app.disable('x-powered-by')
  app.set('trust proxy', true)
  app.use(cors())
  app.use('/', createModuleRouter(descriptor))
  app.use((_req, res) => {
    res.status(404).json({ ok: false, message: `Not found in module “${descriptor.id}”.` })
  })
  return app
}

/** Descriptor metadata in the shape the main app's /api/modules list uses. */
export function moduleSummary(descriptor, mountPath) {
  return {
    id: descriptor.id,
    name: descriptor.name,
    version: descriptor.version || '1.0.0',
    kind: descriptor.kind || descriptor.id,
    enabled: true,
    builtin: true,
    standalone: true,
    url: mountPath,
    description: descriptor.description || descriptor.name,
    uploadedAt: 0,
  }
}
